#!/bin/bash

# Jul 18, 2003
# last modified 2022-12-26

sed -e 's/	/ /g' tex2page.rkt |\
sed -e 's/ \ *$//' |\
sed -e 's/^ *$/END_OF_CURR_EXP/' > my-tex2page

function ignoredef() {
  for f in "$@"
  do
    sed -e '/^(define \ *'$f' *$/,/^END_OF_CURR_EXP/d' my-tex2page |\
    sed -e '/^(define \ *('$f') *$/,/^END_OF_CURR_EXP/d' |\
    sed -e '/^(define \ *('$f' \ *.*$/,/^END_OF_CURR_EXP/d' |\
    sed -e '/^(define \ *'$f' \ *.*$/,/^END_OF_CURR_EXP/d' > .sedtmp
    mv .sedtmp my-tex2page
  done
}

function rename() {
  sed -e 's/'$1'/'$2'/g' my-tex2page > .sedtmp
  mv .sedtmp my-tex2page
}

function uncall() {
  for f in "$@"
  do
    sed -e '/^('$f'/,/^END_OF_CURR_EXP/d' my-tex2page > .sedtmp
    mv .sedtmp my-tex2page
  done
}

ignoredef \
'\*scheme-version\*' \
'\*tex2page-namespace\*' \
call-with-input-string \
eval1 \
strftime string-index string-reverse-index

rename '(define-syntax' '(almost-define-syntax'
rename '(index-of' '(list-index'
rename '(list\*' '(cons*'
rename '(string->keyword' '(string->symbol'

uncall define-namespace-anchor require tex2page

sed -e '/^#!/,/^END_OF_CURR_EXP/d' my-tex2page > .sedtmp
mv .sedtmp my-tex2page

sed -e '/^#lang racket/,/END_OF_CURR_EXP/d' my-tex2page > .sedtmp
mv .sedtmp my-tex2page

cat > guile.preamble <<EOF
#!/bin/sh
exec guile -e main -s \$0 \"\$@\"
!#

(define current-seconds current-time)
(define date-day tm:mday)
(define date-hour tm:hour)
(define date-minute tm:min)
(define date-month tm:mon)
(define date-year tm:year)
(define date-week-day tm:wday)
(define date-dst? tm:isdst)
(define date-time-zone-offset tm:gmtoff)
(define eof the-eof-object)
(define false #f)
(define flush-output force-output)
(define null '())
(define ormap or-map)
(define seconds->date localtime)
(define string-reverse-index string-rindex)
(define true #t)
(define add1 1+)
(define sub1 1-)
(define remove delete)

(define *scheme-version*
  (string-append "Guile " (version)
    (if (getenv "COMSPEC") " windows" " unix")))

(define eval1
  (lambda (e)
    (eval e (interaction-environment))))

(define-macro fluid-let
  (lambda (xvxv . ee)
    (let ((xx (map car xvxv))
          (vv (map cadr xvxv))
          (old-xx (map (lambda (xv)
                         (string->symbol
                          (string-append "%__"
                                         (symbol->string (car xv))))) xvxv))
          (res '%_*_res))
      \`(let ,(map (lambda (old-x x) \`(,old-x ,x)) old-xx xx)
         ,@(map (lambda (x v)
                  \`(set! ,x ,v)) xx vv)
         (let ((,res (begin ,@ee)))
           ,@(map (lambda (x old-x) \`(set! ,x ,old-x)) xx old-xx)
           ,res)))))

(define file-or-directory-modify-seconds
  (lambda (f) (vector-ref (stat f) 9)))

(define read-line
  (lambda (i)
    (let ((c (peek-char i)))
      (if (eof-object? c)
        c
        (let loop ((r (quote ())))
          (let ((c (read-char i)))
            (if (or (eof-object? c) (char=? c #\newline))
              (list->string (reverse! r))
              (loop (cons c r)))))))))

(define-macro almost-define-syntax
  (lambda (name proc)
     \`(define-macro ,name
         (lambda _args
           (let ((datum->syntax (lambda (x y) y))
                 (syntax->datum (lambda (x) x)))
              (,proc (cons 'defstruct _args)))))))

(define main
  (lambda (args)
    (tex2page
      (and (>= (length args) 2)
           (list-ref args 1)))))
EOF

sed -e '1s/^/DUMMY_LINE\n/' my-tex2page |\
sed -e '1r guile.preamble' |\
sed -e '1d' |\
sed -e 's/^END_OF_CURR_EXP.*$//' > .sedtmp
mv .sedtmp my-tex2page
chmod +x my-tex2page

rm -f guile.preamble
